export enum UserRole {
  CITIZEN = 'CITIZEN',
  OFFICER = 'OFFICER',
  DEPT_ADMIN = 'DEPT_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}

export enum IssueStatus {
  SUBMITTED = 'SUBMITTED',
  VALIDATING = 'VALIDATING',
  VALID = 'VALID',
  INVALID = 'INVALID',
  TRIAGED = 'TRIAGED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum IssuePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
